build:
  image: shawnzhu/ruby-nodejs:4.2.2
  environment:
    - LC_ALL=C.UTF-8
    - LANG=en_US.UTF-8
    - LANGUAGE=en_US.UTF-8
  commands:
    - sudo apt-get install -y locales
    - sudo /usr/sbin/locale-gen C.UTF-8
    - sudo /usr/sbin/update-locale LANG=C.UTF-8
    - sudo echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
    - sudo locale-gen
    - bundle install --path .bundle
    - bundle exec jekyll build
