# Site settings
title: Hosted in Space
email: post@hostedinspace.de
description: "Hosted in Space ist Webhosting, Shellhosting, Mailhosting, XMPP-Hosting. Für dich, für mich, für alle. Für alle, denen Datenschutz wichtig ist, sich auf der Kommandozeile wohl fühlen und unixoide Betriebssysteme schöner finden."
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: hostedinspace
stackoverflow_id:
twitter_username: hostedinspace
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
xing_username:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Link
navigation:
 - title: FAQ
   url: /faq/
 - title: Wiki
   url: http://wiki.hostedinspace.de
 - title: Impressum / Kontakt
   url: /impressum/

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     8
sass:
  compressed: true
gems:
  - jekyll-sitemap

exclude: ['Gemfile', 'Gemfile.lock', '.gitkeep']

compress_html:
  clippings: all
  comments: all
